// Redutok launcher, generated by redutok init. No absolute paths: the
// installed package is resolved at runtime from this repository's
// dependencies (chain: repo -> @redutok/meter -> target), or from the
// REDUTOK_HOME environment variable when set.
import { createRequire } from 'node:module';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

try {
  let base = path.join(process.cwd(), 'package.json');
  const home = process.env.REDUTOK_HOME;
  if (home !== undefined && home !== '') base = path.join(home, 'package.json');
  const repoRequire = createRequire(pathToFileURL(base));
  const meterPkg = repoRequire.resolve('@redutok/meter/package.json');
  const entry = createRequire(meterPkg).resolve('@redutok/mcp/main');
  await import(pathToFileURL(entry).href);
} catch (err) {
  console.error('redutok mcp launcher: cannot resolve the installed package: ' + (err instanceof Error ? err.message : String(err)));
  process.exit(1);
}
