import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

/**
 * redutok init and remove. Idempotent, portable install: managed files carry
 * no machine-absolute paths. Hook and MCP entries invoke committed launcher
 * scripts under .claude/redutok/ that resolve the installed packages at
 * runtime through the repo's dependency chain (with a REDUTOK_HOME override),
 * failing open when resolution fails. Hook entries live in
 * .claude/settings.local.json; rationale in docs/RUNNING.md.
 * remove reverts byte-identical from backups taken on first init.
 */

const MANAGED = [
  '.claude/settings.local.json',
  '.claude/redutok/hook.mjs',
  '.claude/redutok/mcp.mjs',
  '.claude/redutok/pipe.mjs',
  '.claude/agents/scout.md',
  '.mcp.json',
  'CLAUDE.md',
];
import { HOOK_EVENT_NAMES } from './claude-compat.js';

// Event names come from the compat shim; matchers are redutok's own scoping.
// PowerShell is matched alongside Bash: the 2026-07-30 rep-1 session ran the
// verify command through the PowerShell tool and bypassed governance entirely.
const HOOK_MATCHERS: Record<string, string> = {
  PreToolUse: 'Read|Bash|PowerShell|Grep|Glob|Write',
  PostToolUse: 'Read|Bash|Edit|Write',
};
const HOOK_EVENTS: { event: string; matcher?: string }[] = HOOK_EVENT_NAMES.map((event) => ({
  event,
  matcher: HOOK_MATCHERS[event],
}));

interface ManifestEntry {
  path: string;
  existed: boolean;
}

interface Manifest {
  version: 1;
  entries: ManifestEntry[];
  createdDirs: string[];
}

export interface LauncherResolution {
  ok: boolean;
  /** Absolute path of the resolved redutok package.json, when ok. */
  packageJson?: string;
  /** Node's own resolution error, when not ok. */
  reason?: string;
}

/** The one instruction that fixes an unresolvable install. */
export const INSTALL_REMEDY = 'npm install --save-dev redutok, then rerun: npx redutok init .';

/**
 * Runs exactly the chain the generated launchers run, ahead of time.
 *
 * init refuses when this fails and doctor reports it, so the launchers, the
 * installer and the diagnostics cannot drift on what "installed" means. The
 * launchers resolve from their own project's directory at hook time, so that
 * -- not the directory redutok happens to be running from -- is what decides
 * whether a setup will work.
 */
export function resolveLauncherChain(targetDir: string): LauncherResolution {
  let base = path.join(targetDir, 'package.json');
  const home = process.env['REDUTOK_HOME'];
  if (home !== undefined && home !== '') base = path.join(home, 'package.json');
  try {
    const packageJson = createRequire(pathToFileURL(base)).resolve('redutok/package.json');
    const fromPackage = createRequire(packageJson);
    fromPackage.resolve('redutok/hook-main');
    fromPackage.resolve('redutok/mcp-main');
    return { ok: true, packageJson };
  } catch (err) {
    return { ok: false, reason: err instanceof Error ? err.message : String(err) };
  }
}

function launcherSource(entrySpec: string, failOpen: boolean): string {
  return `// Redutok launcher, generated by redutok init. No absolute paths: the
// installed package is resolved at runtime from this repository's
// dependencies (chain: repo -> redutok -> target), or from the
// REDUTOK_HOME environment variable when set.
import { createRequire } from 'node:module';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

try {
  let base = path.join(process.cwd(), 'package.json');
  const home = process.env.REDUTOK_HOME;
  if (home !== undefined && home !== '') base = path.join(home, 'package.json');
  const repoRequire = createRequire(pathToFileURL(base));
  const meterPkg = repoRequire.resolve('redutok/package.json');
  const entry = createRequire(meterPkg).resolve('${entrySpec}');
  await import(pathToFileURL(entry).href);
${
  failOpen
    ? '} catch {\n  process.exit(0); // fail-open: a missing install must never break a session\n}'
    : "} catch (err) {\n  console.error('redutok mcp launcher: cannot resolve the installed package: ' + (err instanceof Error ? err.message : String(err)));\n  process.exit(1);\n}"
}
`;
}

/**
 * The pipe launcher differs from the hook/mcp launchers in its fail-open
 * shape: it wraps a real command the model asked to run (`-c <command>`), so
 * when package resolution fails it must still execute that command raw with
 * the exit code preserved — exiting 0 without running anything would corrupt
 * the session (the 2026-07-30 rep-1 run burned ~10 turns of forensics on a
 * rewrite whose bin did not resolve at all). Resolution follows the same
 * dependency chain as the other launchers; the resolved module's main() is
 * called explicitly because its own direct-run guard sees the launcher path
 * in argv[1].
 */
function pipeLauncherSource(): string {
  return `// Redutok pipe launcher, generated by redutok init. No absolute paths: the
// installed package is resolved at runtime from this repository's
// dependencies (chain: repo -> redutok), or from the REDUTOK_HOME
// environment variable when set.
import { createRequire } from 'node:module';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

// Fail-open: the wrapped command still runs raw, exit code preserved. A
// missing install must never break the command the model asked for.
async function runRaw() {
  const i = process.argv.indexOf('-c');
  const command = process.argv[i + 1];
  if (i < 0 || command === undefined) {
    process.stderr.write('redutok pipe launcher: usage: pipe.mjs -c "<command>"\\n');
    process.exit(2);
  }
  const { spawnSync } = await import('node:child_process');
  const run = spawnSync(command, { shell: true, stdio: 'inherit', windowsHide: true });
  process.exit(typeof run.status === 'number' ? run.status : 1);
}

let main;
try {
  let base = path.join(process.cwd(), 'package.json');
  const home = process.env.REDUTOK_HOME;
  if (home !== undefined && home !== '') base = path.join(home, 'package.json');
  const repoRequire = createRequire(pathToFileURL(base));
  const meterPkg = repoRequire.resolve('redutok/package.json');
  const entry = createRequire(meterPkg).resolve('redutok/pipe');
  main = (await import(pathToFileURL(entry).href)).main;
} catch {
  await runRaw();
}
if (typeof main !== 'function') await runRaw();
process.exitCode = await main(process.argv.slice(2));
`;
}

/**
 * Locates an asset that ships alongside this package.
 *
 * Two layouts have to work. In the published tarball scripts/bundle.mjs copies
 * assets to the package root, one level above dist/. In the monorepo they sit
 * at the repository root, three levels above. Only the monorepo path existed
 * before, which is why `redutok init` could never have run from a published
 * install, and why a published daemon answered 503 to every distill request.
 */
function packagedAsset(...rel: string[]): string | undefined {
  const here = path.dirname(fileURLToPath(import.meta.url));
  for (const base of [[here, '..'], [here, '..', '..', '..']]) {
    const candidate = path.join(...base, ...rel);
    if (existsSync(candidate)) return candidate;
  }
  return undefined;
}

/** A document that init splices blocks out of. */
function docPath(name: string): string {
  const found = packagedAsset('docs', name);
  if (found === undefined) throw new Error(`docs/${name} is missing from this install`);
  return found;
}

/** The dcp block shipped with this build, extracted from docs/PROTOCOL.md.
 * Exported so the bench harness can assert a freshly-initialized copy runs
 * the current protocol, not a stale dogfood block. */
export function shippedProtocolBlock(): string {
  const text = readFileSync(docPath('PROTOCOL.md'), 'utf8');
  const match = /<!-- dcp:start v1 -->[\s\S]*?<!-- dcp:end -->/.exec(text);
  if (match === null) throw new Error('docs/PROTOCOL.md is missing the dcp block markers');
  return match[0];
}

/** The dcp block between markers in an existing CLAUDE.md (or protocol.md)
 * body, undefined when no block is present. */
export function extractDcpBlock(text: string): string | undefined {
  return /<!-- dcp:start [\s\S]*?<!-- dcp:end -->/.exec(text)?.[0];
}

/** Architecture-v2 pillar 2: the scout subagent definition, extracted the
 * same way protocolBlock extracts the CLAUDE.md block, from docs/SCOUT.md. */
function scoutAgentBlock(): string {
  const text = readFileSync(docPath('SCOUT.md'), 'utf8');
  // \r?\n: a fresh checkout with autocrlf (Windows CI leg) puts CRLF after
  // the marker; requiring a bare \n made every initRepo call fail there.
  const match = /<!-- scout:start v1 -->\r?\n([\s\S]*?)<!-- scout:end -->/.exec(text);
  if (match === null) throw new Error('docs/SCOUT.md is missing the scout block markers');
  return (match[1] ?? '').trim() + '\n';
}

/** Sidecar defaults persisted per repo in .dcp/config.json (unmanaged, per-machine). */
export const DEFAULT_SIDECAR_PORT = 48642;

/** Port range reserved for per-repo daemons: [42000, 50000). */
const PORT_RANGE_BASE = 42000;
const PORT_RANGE_SIZE = 8000;

/**
 * A stable per-repo port, derived from the repo path (FNV-1a). One shared
 * default port meant the first daemon up served every repo on the machine:
 * the 0.1.1 field install had one repo's distill events in another repo's
 * audit trail, and every cross-repo zoom refused. A hash can still collide,
 * so the repo-identity handshake stays the backstop; this just makes two
 * repos sharing a port the exception instead of the rule. Separators and
 * (win32-style) case are folded so both spellings of one path agree.
 */
export function portForRepo(repoDir: string): number {
  const key = repoDir.replace(/\\/g, '/').replace(/\/+$/, '').toLowerCase();
  let hash = 0x811c9dc5;
  for (let i = 0; i < key.length; i += 1) {
    hash ^= key.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return PORT_RANGE_BASE + (hash % PORT_RANGE_SIZE);
}

function writeDcpConfig(dcpDir: string, targetDir: string): void {
  // The daemon loads its distillation profiles from here at startup and
  // answers 503 to /distill without them, so this has to resolve in a
  // published install, not just in the monorepo.
  const profilesDir = packagedAsset('profiles');
  writeFileSync(
    path.join(dcpDir, 'config.json'),
    JSON.stringify({ port: portForRepo(path.resolve(targetDir)), profilesDir }, null, 2) + '\n',
    'utf8',
  );
}

export function initRepo(targetDir: string): string {
  // Refuse before writing anything. The launchers resolve redutok from this
  // project at hook time, and npx runs from a temporary cache that is never in
  // the project's node_modules -- so a bare `npx redutok init` used to write a
  // setup where the MCP server died at startup and every hook silently
  // no-opped. Half a setup is worse than none: the files would look installed.
  const resolution = resolveLauncherChain(targetDir);
  if (!resolution.ok) {
    throw new Error(
      `redutok cannot be resolved from ${path.resolve(targetDir)}, so the launchers this would write could not load it.\n` +
        'Running init straight from npx does this: npx executes out of a temporary cache that is never part\n' +
        "of the project's node_modules, so the MCP server dies at startup and the hooks silently no-op.\n\n" +
        `  ${INSTALL_REMEDY}\n\n` +
        'If the install lives outside the project, point REDUTOK_HOME at the directory that holds it.\n' +
        `(resolution error: ${resolution.reason})`,
    );
  }

  const dcpDir = path.join(targetDir, '.dcp');
  const backupDir = path.join(dcpDir, 'backup');
  const manifestPath = path.join(backupDir, 'manifest.json');

  if (!existsSync(manifestPath)) {
    const createdDirs: string[] = [];
    for (const dir of [
      dcpDir,
      backupDir,
      path.join(targetDir, '.claude'),
      path.join(targetDir, '.claude', 'redutok'),
      path.join(targetDir, '.claude', 'agents'),
    ]) {
      if (!existsSync(dir)) {
        mkdirSync(dir, { recursive: true });
        createdDirs.push(path.relative(targetDir, dir).replace(/\\/g, '/'));
      }
    }
    const entries: ManifestEntry[] = MANAGED.map((rel) => {
      const full = path.join(targetDir, rel);
      const existed = existsSync(full);
      if (existed) copyFileSync(full, path.join(backupDir, rel.replace(/[/\\]/g, '__')));
      return { path: rel, existed };
    });
    const manifest: Manifest = { version: 1, entries, createdDirs };
    writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  }

  writeFileSync(
    path.join(targetDir, '.claude', 'redutok', 'hook.mjs'),
    // redutok/hook-main, not @redutok/hooks/hook-main: the scoped packages are
    // private and inlined into this package's dist/, so the old specifier
    // resolves to nothing in a consumer's tree.
    launcherSource('redutok/hook-main', true),
    'utf8',
  );
  writeFileSync(
    path.join(targetDir, '.claude', 'redutok', 'mcp.mjs'),
    launcherSource('redutok/mcp-main', false),
    'utf8',
  );
  writeFileSync(
    path.join(targetDir, '.claude', 'redutok', 'pipe.mjs'),
    pipeLauncherSource(),
    'utf8',
  );
  // mkdirSync here too, not just in the first-init createdDirs block above:
  // a repo initialized before the scout subagent existed has no
  // .claude/agents directory yet, and a plain re-init must still create it.
  mkdirSync(path.join(targetDir, '.claude', 'agents'), { recursive: true });
  writeFileSync(path.join(targetDir, '.claude', 'agents', 'scout.md'), scoutAgentBlock(), 'utf8');

  const settingsPath = path.join(targetDir, '.claude', 'settings.local.json');
  const settings = existsSync(settingsPath)
    ? (JSON.parse(readFileSync(settingsPath, 'utf8')) as Record<string, unknown>)
    : {};
  const hooks = (settings['hooks'] ?? {}) as Record<string, unknown[]>;
  for (const { event, matcher } of HOOK_EVENTS) {
    const command = `node .claude/redutok/hook.mjs ${event}`;
    const existing = (hooks[event] ?? []).filter(
      (entry) => !JSON.stringify(entry).includes('redutok/hook.mjs') && !JSON.stringify(entry).includes('hook-main.js'),
    );
    const entry: Record<string, unknown> = { hooks: [{ type: 'command', command }] };
    if (matcher !== undefined) entry['matcher'] = matcher;
    hooks[event] = [...existing, entry];
  }
  settings['hooks'] = hooks;
  writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf8');

  const mcpPath = path.join(targetDir, '.mcp.json');
  const mcpConfig = existsSync(mcpPath)
    ? (JSON.parse(readFileSync(mcpPath, 'utf8')) as Record<string, unknown>)
    : {};
  const servers = (mcpConfig['mcpServers'] ?? {}) as Record<string, unknown>;
  // No REDUTOK_PORT here: the MCP entry resolves the port from this repo's
  // .dcp/config.json, so every copy of a repo targets its own daemon. A
  // hardcoded port made bench temp copies talk to the dogfood daemon.
  servers['redutok'] = {
    command: 'node',
    args: ['.claude/redutok/mcp.mjs'],
    env: { REDUTOK_DCP_DIR: '.dcp' },
  };
  mcpConfig['mcpServers'] = servers;
  writeFileSync(mcpPath, JSON.stringify(mcpConfig, null, 2) + '\n', 'utf8');

  const block = shippedProtocolBlock();
  const claudeMdPath = path.join(targetDir, 'CLAUDE.md');
  let claudeMd = existsSync(claudeMdPath) ? readFileSync(claudeMdPath, 'utf8') : '';
  if (/<!-- dcp:start [\s\S]*?<!-- dcp:end -->/.test(claudeMd)) {
    claudeMd = claudeMd.replace(/<!-- dcp:start [\s\S]*?<!-- dcp:end -->/, block);
  } else {
    claudeMd = claudeMd === '' ? block + '\n' : claudeMd.replace(/\n*$/, '\n\n') + block + '\n';
  }
  writeFileSync(claudeMdPath, claudeMd, 'utf8');

  writeFileSync(path.join(dcpDir, 'protocol.md'), block + '\n', 'utf8');
  writeDcpConfig(dcpDir, targetDir);
  return `Redutok installed into ${targetDir}. Hooks, MCP server, and protocol block are in place. Run redutok up to start the sidecar.`;
}

export function removeRepo(targetDir: string): string {
  const dcpDir = path.join(targetDir, '.dcp');
  const backupDir = path.join(dcpDir, 'backup');
  const manifestPath = path.join(backupDir, 'manifest.json');
  if (!existsSync(manifestPath)) {
    return 'Nothing to remove: no .dcp/backup/manifest.json found. Was redutok init run here?';
  }
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as Manifest;
  for (const entry of manifest.entries) {
    const full = path.join(targetDir, entry.path);
    if (entry.existed) {
      copyFileSync(path.join(backupDir, entry.path.replace(/[/\\]/g, '__')), full);
    } else if (existsSync(full)) {
      rmSync(full);
    }
  }
  rmSync(dcpDir, { recursive: true, force: true });
  for (const rel of [...manifest.createdDirs].sort((a, b) => b.length - a.length)) {
    const full = path.join(targetDir, rel);
    if (existsSync(full) && readdirSync(full).length === 0) rmSync(full, { recursive: true });
  }
  return `Redutok removed from ${targetDir}; managed files restored byte-identical.`;
}
