import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * redutok init and remove. Idempotent, portable install: managed files carry
 * no machine-absolute paths. Hook and MCP entries invoke committed launcher
 * scripts under .claude/redutok/ that resolve the installed packages at
 * runtime through the repo's dependency chain (with a REDUTOK_HOME override),
 * failing open when resolution fails. Hook entries live in
 * .claude/settings.local.json; rationale in docs/RUNNING.md.
 * remove reverts byte-identical from backups taken on first init.
 */

const MANAGED = [
  '.claude/settings.local.json',
  '.claude/redutok/hook.mjs',
  '.claude/redutok/mcp.mjs',
  '.claude/agents/scout.md',
  '.mcp.json',
  'CLAUDE.md',
];
import { HOOK_EVENT_NAMES } from './claude-compat.js';

// Event names come from the compat shim; matchers are redutok's own scoping.
const HOOK_MATCHERS: Record<string, string> = {
  PreToolUse: 'Read|Bash|Grep|Glob|Write',
  PostToolUse: 'Read|Bash|Edit|Write',
};
const HOOK_EVENTS: { event: string; matcher?: string }[] = HOOK_EVENT_NAMES.map((event) => ({
  event,
  matcher: HOOK_MATCHERS[event],
}));

interface ManifestEntry {
  path: string;
  existed: boolean;
}

interface Manifest {
  version: 1;
  entries: ManifestEntry[];
  createdDirs: string[];
}

const require = createRequire(import.meta.url);

function launcherSource(entrySpec: string, failOpen: boolean): string {
  return `// Redutok launcher, generated by redutok init. No absolute paths: the
// installed package is resolved at runtime from this repository's
// dependencies (chain: repo -> redutok -> target), or from the
// REDUTOK_HOME environment variable when set.
import { createRequire } from 'node:module';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

try {
  let base = path.join(process.cwd(), 'package.json');
  const home = process.env.REDUTOK_HOME;
  if (home !== undefined && home !== '') base = path.join(home, 'package.json');
  const repoRequire = createRequire(pathToFileURL(base));
  const meterPkg = repoRequire.resolve('redutok/package.json');
  const entry = createRequire(meterPkg).resolve('${entrySpec}');
  await import(pathToFileURL(entry).href);
${
  failOpen
    ? '} catch {\n  process.exit(0); // fail-open: a missing install must never break a session\n}'
    : "} catch (err) {\n  console.error('redutok mcp launcher: cannot resolve the installed package: ' + (err instanceof Error ? err.message : String(err)));\n  process.exit(1);\n}"
}
`;
}

function protocolBlock(): string {
  const protocolPath = path.join(
    path.dirname(fileURLToPath(import.meta.url)),
    '..', '..', '..', 'docs', 'PROTOCOL.md',
  );
  const text = readFileSync(protocolPath, 'utf8');
  const match = /<!-- dcp:start v1 -->[\s\S]*?<!-- dcp:end -->/.exec(text);
  if (match === null) throw new Error('docs/PROTOCOL.md is missing the dcp block markers');
  return match[0];
}

/** Architecture-v2 pillar 2: the scout subagent definition, extracted the
 * same way protocolBlock extracts the CLAUDE.md block, from docs/SCOUT.md. */
function scoutAgentBlock(): string {
  const scoutPath = path.join(
    path.dirname(fileURLToPath(import.meta.url)),
    '..', '..', '..', 'docs', 'SCOUT.md',
  );
  const text = readFileSync(scoutPath, 'utf8');
  // \r?\n: a fresh checkout with autocrlf (Windows CI leg) puts CRLF after
  // the marker; requiring a bare \n made every initRepo call fail there.
  const match = /<!-- scout:start v1 -->\r?\n([\s\S]*?)<!-- scout:end -->/.exec(text);
  if (match === null) throw new Error('docs/SCOUT.md is missing the scout block markers');
  return (match[1] ?? '').trim() + '\n';
}

/** Sidecar defaults persisted per repo in .dcp/config.json (unmanaged, per-machine). */
export const DEFAULT_SIDECAR_PORT = 48642;

function writeDcpConfig(dcpDir: string): void {
  let profilesDir: string | undefined;
  try {
    const sidecarPkg = require.resolve('@redutok/sidecar/package.json');
    const candidate = path.join(path.dirname(sidecarPkg), '..', '..', 'profiles');
    if (existsSync(candidate)) profilesDir = candidate;
  } catch {
    profilesDir = undefined;
  }
  writeFileSync(
    path.join(dcpDir, 'config.json'),
    JSON.stringify({ port: DEFAULT_SIDECAR_PORT, profilesDir }, null, 2) + '\n',
    'utf8',
  );
}

export function initRepo(targetDir: string): string {
  const dcpDir = path.join(targetDir, '.dcp');
  const backupDir = path.join(dcpDir, 'backup');
  const manifestPath = path.join(backupDir, 'manifest.json');

  if (!existsSync(manifestPath)) {
    const createdDirs: string[] = [];
    for (const dir of [
      dcpDir,
      backupDir,
      path.join(targetDir, '.claude'),
      path.join(targetDir, '.claude', 'redutok'),
      path.join(targetDir, '.claude', 'agents'),
    ]) {
      if (!existsSync(dir)) {
        mkdirSync(dir, { recursive: true });
        createdDirs.push(path.relative(targetDir, dir).replace(/\\/g, '/'));
      }
    }
    const entries: ManifestEntry[] = MANAGED.map((rel) => {
      const full = path.join(targetDir, rel);
      const existed = existsSync(full);
      if (existed) copyFileSync(full, path.join(backupDir, rel.replace(/[/\\]/g, '__')));
      return { path: rel, existed };
    });
    const manifest: Manifest = { version: 1, entries, createdDirs };
    writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  }

  writeFileSync(
    path.join(targetDir, '.claude', 'redutok', 'hook.mjs'),
    launcherSource('@redutok/hooks/hook-main', true),
    'utf8',
  );
  writeFileSync(
    path.join(targetDir, '.claude', 'redutok', 'mcp.mjs'),
    launcherSource('@redutok/mcp/main', false),
    'utf8',
  );
  // mkdirSync here too, not just in the first-init createdDirs block above:
  // a repo initialized before the scout subagent existed has no
  // .claude/agents directory yet, and a plain re-init must still create it.
  mkdirSync(path.join(targetDir, '.claude', 'agents'), { recursive: true });
  writeFileSync(path.join(targetDir, '.claude', 'agents', 'scout.md'), scoutAgentBlock(), 'utf8');

  const settingsPath = path.join(targetDir, '.claude', 'settings.local.json');
  const settings = existsSync(settingsPath)
    ? (JSON.parse(readFileSync(settingsPath, 'utf8')) as Record<string, unknown>)
    : {};
  const hooks = (settings['hooks'] ?? {}) as Record<string, unknown[]>;
  for (const { event, matcher } of HOOK_EVENTS) {
    const command = `node .claude/redutok/hook.mjs ${event}`;
    const existing = (hooks[event] ?? []).filter(
      (entry) => !JSON.stringify(entry).includes('redutok/hook.mjs') && !JSON.stringify(entry).includes('hook-main.js'),
    );
    const entry: Record<string, unknown> = { hooks: [{ type: 'command', command }] };
    if (matcher !== undefined) entry['matcher'] = matcher;
    hooks[event] = [...existing, entry];
  }
  settings['hooks'] = hooks;
  writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf8');

  const mcpPath = path.join(targetDir, '.mcp.json');
  const mcpConfig = existsSync(mcpPath)
    ? (JSON.parse(readFileSync(mcpPath, 'utf8')) as Record<string, unknown>)
    : {};
  const servers = (mcpConfig['mcpServers'] ?? {}) as Record<string, unknown>;
  servers['redutok'] = {
    command: 'node',
    args: ['.claude/redutok/mcp.mjs'],
    env: { REDUTOK_PORT: String(DEFAULT_SIDECAR_PORT), REDUTOK_DCP_DIR: '.dcp' },
  };
  mcpConfig['mcpServers'] = servers;
  writeFileSync(mcpPath, JSON.stringify(mcpConfig, null, 2) + '\n', 'utf8');

  const block = protocolBlock();
  const claudeMdPath = path.join(targetDir, 'CLAUDE.md');
  let claudeMd = existsSync(claudeMdPath) ? readFileSync(claudeMdPath, 'utf8') : '';
  if (/<!-- dcp:start [\s\S]*?<!-- dcp:end -->/.test(claudeMd)) {
    claudeMd = claudeMd.replace(/<!-- dcp:start [\s\S]*?<!-- dcp:end -->/, block);
  } else {
    claudeMd = claudeMd === '' ? block + '\n' : claudeMd.replace(/\n*$/, '\n\n') + block + '\n';
  }
  writeFileSync(claudeMdPath, claudeMd, 'utf8');

  writeFileSync(path.join(dcpDir, 'protocol.md'), block + '\n', 'utf8');
  writeDcpConfig(dcpDir);
  return `Redutok installed into ${targetDir}. Hooks, MCP server, and protocol block are in place. Run redutok up to start the sidecar.`;
}

export function removeRepo(targetDir: string): string {
  const dcpDir = path.join(targetDir, '.dcp');
  const backupDir = path.join(dcpDir, 'backup');
  const manifestPath = path.join(backupDir, 'manifest.json');
  if (!existsSync(manifestPath)) {
    return 'Nothing to remove: no .dcp/backup/manifest.json found. Was redutok init run here?';
  }
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as Manifest;
  for (const entry of manifest.entries) {
    const full = path.join(targetDir, entry.path);
    if (entry.existed) {
      copyFileSync(path.join(backupDir, entry.path.replace(/[/\\]/g, '__')), full);
    } else if (existsSync(full)) {
      rmSync(full);
    }
  }
  rmSync(dcpDir, { recursive: true, force: true });
  for (const rel of [...manifest.createdDirs].sort((a, b) => b.length - a.length)) {
    const full = path.join(targetDir, rel);
    if (existsSync(full) && readdirSync(full).length === 0) rmSync(full, { recursive: true });
  }
  return `Redutok removed from ${targetDir}; managed files restored byte-identical.`;
}
